/**
 * States
 */
export enum FSMStates {
    PAUSED = 'PAUSED',
    INIT = 'INIT',
    GROUND_SELECTED = 'GROUND_SELECTED',
    GOAL_SELECTED = 'GOAL_SELECTED',
    SELECTED_PLAYER = 'SELECTED_PLAYER',
    DEFENSE = 'DEFENSE',
    GAME_STARTED = 'GAME_STARTED',
    ATTACK = 'ATTACK',
    RETURN_TO_SELECTED_PLAYER = 'RETURN_TO_SELECTED_PLAYER',
    GOAL_LEAVED = 'GOAL_LEAVED',
    GROUND_LEAVED = 'GROUND_LEAVED',
    GAME_ENDED = 'GAME_ENDED'
}